# Generated by Django 5.0.6 on 2024-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='profesor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
