# Generated by Django 5.0.6 on 2024-06-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_proyecto_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='id',
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
