# Generated by Django 5.0.6 on 2024-06-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_proyecto_id_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
